Converts tabs to spaces

diff --git a/systemd-query b/systemd-query
--- a/systemd-query
+++ b/systemd-query
@@ -3,50 +3,50 @@
 # Require BASH >= 4.0
 if [ $BASH_VERSINFO -lt 4 ];
 then
-	echo "BASH >= 4.0 is required."
-	exit 1
+    echo "BASH >= 4.0 is required."
+    exit 1
 fi
 
 list() {
-	
-	command="systemctl list-unit-files --type=service"
-	
-	case $1 in
-	enabled | disabled)
-		$command | grep $1 | less;;
-	all)
-		$command | less;;
-	*)
-		echo "Usage: $0 list (enabled | disabled | all)"
-		exit 1;;
+
+    command="systemctl list-unit-files --type=service"
+
+    case $1 in
+    enabled | disabled)
+        $command | grep $1 | less;;
+    all)
+        $command | less;;
+    *)
+        echo "Usage: $0 list (enabled | disabled | all)"
+        exit 1;;
     esac
 }
 
 onoff() {
-	command="systemctl -q $1 $2.service"
-	
-	if [ -n "$2" ];
-	then
-		$command
-		if [ $? -eq 0  ] || [ "$1" = "status" ];
-		then
-			echo -e "[ \e[01;32mOK\e[0m ]\t${1^} service $2"
-		else
-			echo -e "[ \e[01;31m!!\e[0m ]\tSomenthing goes wrong. Cannot $1 service $2"
-			exit 1
-		fi
-	else
-		echo -e "Usage: $0 ( start | stop | restart | status) \e[01;31mservice\e[0m"
-		exit 1
-	fi
+    command="systemctl -q $1 $2.service"
+
+    if [ -n "$2" ];
+    then
+        $command
+        if [ $? -eq 0  ] || [ "$1" = "status" ];
+        then
+            echo -e "[ \e[01;32mOK\e[0m ]\t${1^} service $2"
+        else
+            echo -e "[ \e[01;31m!!\e[0m ]\tSomenthing goes wrong. Cannot $1 service $2"
+            exit 1
+        fi
+    else
+        echo -e "Usage: $0 ( start | stop | restart | status) \e[01;31mservice\e[0m"
+        exit 1
+    fi
 }
 
 case $1 in
 list)
-	list $2;;
+    list $2;;
 enable | disable | start | stop | restart | status)
-	onoff $1 $2;;
+    onoff $1 $2;;
 *)
-	echo "Usage: $0 (list | enable | disable | start | stop | restart | status)";;
+    echo "Usage: $0 (list | enable | disable | start | stop | restart | status)";;
 esac
 exit 0
