Check if parameter "service" is not empty where required.

diff --git a/systemd-query b/systemd-query
--- a/systemd-query
+++ b/systemd-query
@@ -1,11 +1,6 @@
 #!/bin/bash
 
 # Require BASH >= 4.0
-if [ $BASH_VERSINFO -lt 4 ];
-then
-	echo "BASH >= 4.0 is required."
-	exit 1
-fi
 
 list() {
 	
@@ -24,16 +19,21 @@ list() {
 
 onoff() {
 	command="systemctl -q $1 $2.service"
-	$command
 	
-	if [ $? -eq 0 ];
+	if [ -n "$2" ];
 	then
-		echo -e "[ \e[0;32mOK\e[0m ]\t${1^} service $2"
+		$command
+		if [ $? -eq 0  ] || [ "$1" = "status" ];
+		then
+			echo -e "[ \e[01;32mOK\e[0m ]\t${1^} service $2"
+		else
+			echo -e "[ \e[01;31m!!\e[0m ]\tSomenthing goes wrong. Cannot $1 service $2"
+			exit 1
+		fi
 	else
-		echo -e "[ \e[0;31m!!\e[0m ]\tSomenthing goes wrong. Cannot $1 service $2"
+		echo -e "Usage: $0 ( start | stop | restart | status) \e[01;31mservice\e[0m"
 		exit 1
 	fi
-	
 }
 
 case $1 in
